### ISSUE TITLE
Does not compile with GCC 7.1.1

### ISSUE THREAD

**Issue by petamem** [Creepsky/creepMiner#133]
This funny program will not compile with GCC 7.1.1

# make
g++ -O3 -march=core2 -std=c++11 -Wall -D_REENTRANT -DNDEBUG -DLOG_TERMINAL -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/MinerLogger.cpp -o bin/obj/MinerLogger.o
In file included from src/MinerLogger.cpp:9:0:
src/MinerLogger.hpp:125:68: error: ‘std::function’ has not been declared
   static void writeAndFunc(Burst::MinerLogger::TextType type, std::function<void()> func);

etc. etc.

Neither 1.5.2 nor the 1.6.0 development branch. With GCC 5.4.0 and also 6.3.0 it works.
(changing -std=c++11 back and forth to c++14 has also no effect)

So avoid 7.1.1 for now.

**Comment by Creepsky** [comment]
@petamem yes, there was someone in the gitter chat with the same issue.
Will push a fix into development right now.

**Comment by Creepsky** [comment]
@petamem Please try if it is compilable now (development branch).

**Comment by llybin** [comment]
@Creepsky Thank you, the problem is solved in a development branch.
