### ISSUE TITLE
Assistance compiling on vanilla FreeBSD 11.1

### ISSUE THREAD

**Issue by GoodbyeWorld** [Creepsky/creepMiner#276]
Subject says it all - I'm wondering if someone more familiar with compiling on FreeBSD would mind providing some tips.  Starting from a clean install.  Thank you.

**Comment by Creepsky** [comment]
What is not working? What did you try?

**Comment by GoodbyeWorld** [comment]
Sure!  Step-by-step:

1. Install FreeBSD 11.1.  I included the src package, but this might not matter.
2. Install python - `pkg install python27`
3. Install pip - `python2.7 -m ensurepip`
4. Install conan - `pip install conan`
5. Install sqlite - `pkg install py27-sqlite3`
6. Install bash - `pkg install bash`
7. Install perl - `pkg install perl5`
8. Install cmake - `pkg install cmake`
9. Install wget - `pkg install wget`. 
10. Download and untar the latest release of creepMiner
11. cd into the creepMiner directory
12. Run conan - `conan install . --build zlib --build OpenSSL --build Poco`

This is where we have some problems.  Poco fails to compile, with the following errors:

`
[  0%] Building CXX object Foundation/CMakeFiles/Foundation.dir/src/ASCIIEncoding.cpp.o
In file included from /root/.conan/data/Poco/1.8.0.1/pocoproject/stable/build/df19227a21af2d66ac57533a2184c19f5cc25f11/poco/Foundation/src/ASCIIEncoding.cpp:15:
In file included from /root/.conan/data/Poco/1.8.0.1/pocoproject/stable/build/df19227a21af2d66ac57533a2184c19f5cc25f11/poco/Foundation/include/Poco/ASCIIEncoding.h:21:
In file included from /root/.conan/data/Poco/1.8.0.1/pocoproject/stable/build/df19227a21af2d66ac57533a2184c19f5cc25f11/poco/Foundation/include/Poco/Foundation.h:163:
In file included from /root/.conan/data/Poco/1.8.0.1/pocoproject/stable/build/df19227a21af2d66ac57533a2184c19f5cc25f11/poco/Foundation/include/Poco/Bugcheck.h:22:
In file included from /usr/include/c++/v1/string:470:
In file included from /usr/include/c++/v1/string_view:171:
In file included from /usr/include/c++/v1/__string:57:
/usr/include/c++/v1/cstdio:121:9: error: no member named 'snprintf' in the global namespace
using ::snprintf;
      ~~^
/usr/include/c++/v1/cstdio:125:9: error: no member named 'vfscanf' in the global namespace; did you mean 'fscanf'?
using ::vfscanf;
      ~~^
`

Poco is available as a binary package via `pkg install poco`, as are OpenSSL and zlib of course.  I've tried installing them that way, and just commenting out poco line in the `[requires]` section of the in the

**Comment by GoodbyeWorld** [comment]
Update:

I should have mentioned I'm working with 2.8 (above).

I tried using the CMake-only version of building this, and installed Poco.

1. Install Poco `pkg install poco`
2. Set the Poco root environment variable: `POCO_ROOT=/usr/local/include/Poco`
3. Rename the CMake file: `mv CMakeLists-Original.txt CMakeLists.txt`
4. Run CMake: `cmake CMakeLists.txt -DNO_GPU=ON -DCMAKE_BUILD_TYPE=RELEASE -DUSE_SSE4=on -DUSE_AVX=off -DUSE_AVX=off -DUSE_AVX2=off -DUSE_CUDA=off -DUSE_OPENCL=off``
5. Run make: `make`

It ALMOST worked:
````
[ 83%] Building CXX object CMakeFiles/creepMiner.dir/src/webserver/RequestHandler.cpp.o
[ 86%] Building CXX object CMakeFiles/creepMiner.dir/src/Declarations.cpp.o
[ 88%] Building CXX object CMakeFiles/creepMiner.dir/src/main.cpp.o
[ 91%] Building CXX object CMakeFiles/creepMiner.dir/src/MinerUtil.cpp.o
[ 94%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/Performance.cpp.o
[ 97%] Building CXX object CMakeFiles/creepMiner.dir/src/shabal/mshabal/mshabal_sse4.cpp.o
[100%] Linking CXX executable bin/creepMiner
CMakeFiles/creepMiner.dir/src/main.cpp.o: In function `main':
/root/build/creepMiner-2.8.0/src/main.cpp:(.text+0x11ea): undefined reference to `Burst::Setup::setup(Burst::MinerConfig&)'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /root/build/creepMiner-2.8.0
*** Error code 1

Stop.
make[1]: stopped in /root/build/creepMiner-2.8.0
*** Error code 1

Stop.
make: stopped in /root/build/creepMiner-2.8.0
[root@devil ~/build/creepMiner-2.8.0]#
````

Building 2.7.x worked this way, on the same system FYI.  I didn't need to rename the CMake file, it just worked.

**Comment by Creepsky** [comment]
What is your `gcc --version`?

First try `conan install . --build=missing -s compiler.libcxx=libstdc++11` with the new CMakeLists.txt (like described here: https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-Conan).

Version 1.8+ will use conan + cmake as build chain, the old cmakelists is obsolete and will be deleted whenever 1.8* will be released.

To fix your error with the old CMakeLists.txt clone the project: `git clone https://github.com/Creepsky/creepMiner`, change the directory: `cd creepMiner`, and then switch to the development branch: `git checkout development`.
Then again rename the CMakeLists and use your cmake command.
